name: lerobot
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - expat=2.7.4
  - ld_impl_linux-64=2.44
  - libexpat=2.7.4
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libnsl=2.0.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.5.5
  - packaging=25.0
  - pip=26.0.1
  - pthread-stubs=0.3
  - python=3.10.19
  - readline=8.3
  - setuptools=80.10.2
  - sqlite=3.51.1
  - tk=8.6.15
  - tzdata=2025c
  - wheel=0.46.3
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - accelerate==1.12.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - anyio==4.12.1
      - async-timeout==5.0.1
      - attrs==25.4.0
      - av==15.1.0
      - certifi==2026.2.25
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cloudpickle==3.1.2
      - cmake==4.1.3
      - cuda-bindings==12.9.4
      - cuda-pathfinder==1.4.0
      - datasets==4.6.1
      - deepdiff==8.6.1
      - diffusers==0.35.2
      - draccus==0.10.0
      - einops==0.8.2
      - evdev==1.9.3
      - exceptiongroup==1.3.1
      - farama-notifications==0.0.4
      - frozenlist==1.8.0
      - gitdb==4.0.12
      - gitpython==3.1.46
      - gymnasium==1.2.3
      - h11==0.16.0
      - hf-transfer==0.1.9
      - hf-xet==1.3.2
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.35.3
      - idna==3.11
      - imageio==2.37.2
      - imageio-ffmpeg==0.6.0
      - importlib-metadata==8.7.1
      - inquirerpy==0.3.4
      - jinja2==3.1.6
      - jsonlines==4.0.0
      - lerobot==0.4.4
      - markupsafe==3.0.3
      - mergedeep==1.3.4
      - mpmath==1.3.0
      - multidict==6.7.1
      - mypy-extensions==1.1.0
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.4.5
      - nvidia-nvtx-cu12==12.8.90
      - opencv-python-headless==4.12.0.88
      - orderly-set==5.5.0
      - pfzy==0.3.4
      - pillow==12.1.1
      - platformdirs==4.9.2
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - psutil==7.2.2
      - pyarrow==23.0.1
      - pynput==1.8.1
      - pyserial==3.5
      - python-xlib==0.33
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyyaml-include==1.4.1
      - rerun-sdk==0.26.2
      - sentry-sdk==2.53.0
      - six==1.17.0
      - smmap==5.0.2
      - sympy==1.14.0
      - termcolor==3.3.0
      - toml==0.10.2
      - torch==2.10.0
      - torchcodec==0.10.0
      - torchvision==0.25.0
      - triton==3.6.0
      - typing-inspect==0.9.0
      - urllib3==2.6.3
      - wandb==0.24.2
      - wcwidth==0.6.0
      - yarl==1.22.0
      - zipp==3.23.0
